import { Product } from '@/types'

// 26 個商品的靜態資料 — 含能量標籤，用於能量測試演算法
// 商品圖片先用 unsplash placeholder，使用者上線後可從 Supabase 替換

const ph = (q: string) =>
  `https://images.unsplash.com/${q}?w=800&auto=format&fit=crop`

export const PRODUCTS: Product[] = [
  // ========== A. 單方草本系列（8 款）==========
  {
    id: 'h1', slug: 'white-sage', name: '白鼠尾草',
    subtitle: '強力淨化・驅除負能量',
    description: '純天然加州白鼠尾草，最廣泛使用的淨化香草。煙霧能瓦解空間中的混亂能量，特別適合搬家、爭吵後或感覺氣場混亂時使用。',
    ingredients: ['加州白鼠尾草'],
    price: 280, stock: 50, featured: true, created_at: '',
    images: [ph('photo-1600880292203-757bb62b4baf')],
    category: 'herbs',
    mood_tags: ['anxious', 'angry'],
    luck_tags: ['unlucky', 'newspace'],
    elements: ['fire'],
  },
  {
    id: 'h2', slug: 'palo-santo', name: '祕魯聖木',
    subtitle: '淨化提振・轉換氛圍',
    description: '來自秘魯的天然聖木，溫暖木質香氣帶來保護與祝福。不僅淨化，還能提振心情，是工作前、冥想或低落時的最佳夥伴。',
    ingredients: ['秘魯聖木 Palo Santo'],
    price: 320, stock: 40, featured: true, created_at: '',
    images: [ph('photo-1604480132736-44c188fe4d20')],
    category: 'herbs',
    mood_tags: ['low', 'tired'],
    luck_tags: ['career', 'newplan'],
    elements: ['fire', 'wood'],
  },
  {
    id: 'h3', slug: 'lavender', name: '薰衣草',
    subtitle: '安撫・放鬆・助眠',
    description: '經典舒緩香草，柔和花香能撫平緊張神經。適合焦慮、失眠、需要放鬆的夜晚。',
    ingredients: ['乾燥薰衣草'],
    price: 260, stock: 60, featured: true, created_at: '',
    images: [ph('photo-1499002238440-d264edd596ec')],
    category: 'herbs',
    mood_tags: ['anxious', 'low'],
    luck_tags: ['health'],
    elements: ['wind', 'water'],
  },
  {
    id: 'h4', slug: 'sweetgrass', name: '北美聖草',
    subtitle: '召喚正能量・儀式祝福',
    description: '北美原住民傳統儀式用草，香甜氣息能召喚正向能量。適合新計畫啟動、感謝儀式或祈福場合。',
    ingredients: ['北美聖草 Sweetgrass'],
    price: 380, stock: 25, featured: false, created_at: '',
    images: [ph('photo-1568571780765-9276ac8b75a2')],
    category: 'herbs',
    mood_tags: ['lost', 'joyful'],
    luck_tags: ['newplan'],
    elements: ['wind'],
  },
  {
    id: 'h5', slug: 'dragons-blood', name: '龍血草',
    subtitle: '強化保護・增強意志',
    description: '濃郁深沉的木質香，建立強大的能量界線。適合事業挑戰、想立下界線、或感受到外在干擾時使用。',
    ingredients: ['龍血樹脂'],
    price: 420, stock: 20, featured: false, created_at: '',
    images: [ph('photo-1602928298849-325cec8771c0')],
    category: 'herbs',
    mood_tags: ['angry', 'tired'],
    luck_tags: ['career', 'newspace'],
    elements: ['fire'],
  },
  {
    id: 'h6', slug: 'eucalyptus', name: '尤加利葉',
    subtitle: '清新・淨化呼吸・療癒',
    description: '清新薄荷木質香，特別淨化呼吸道與沉悶空間。病後康復、冬季濕冷或空間不通風時的療癒選擇。',
    ingredients: ['尤加利葉'],
    price: 280, stock: 35, featured: false, created_at: '',
    images: [ph('photo-1531956531700-dc0ee0f1f9a5')],
    category: 'herbs',
    mood_tags: ['tired'],
    luck_tags: ['health'],
    elements: ['wind'],
  },
  {
    id: 'h7', slug: 'rosemary', name: '迷迭香',
    subtitle: '提升記憶・增強專注',
    description: '清晰銳利的香氣，幫助頭腦清晰、專注力提升。考試、創作、新計畫啟動時的好夥伴。',
    ingredients: ['乾燥迷迭香'],
    price: 280, stock: 30, featured: false, created_at: '',
    images: [ph('photo-1515426954832-92d0fd0e1abf')],
    category: 'herbs',
    mood_tags: ['lost', 'joyful'],
    luck_tags: ['career', 'newplan'],
    elements: ['fire'],
  },
  {
    id: 'h8', slug: 'cedar', name: '雪松',
    subtitle: '穩定・扎根・保護',
    description: '深沉溫暖的木質香，將飄忽的能量帶回大地。心神不寧、剛搬家、需要安定感時的最佳選擇。',
    ingredients: ['雪松木屑'],
    price: 320, stock: 25, featured: true, created_at: '',
    images: [ph('photo-1542728928-1413d1894ed1')],
    category: 'herbs',
    mood_tags: ['anxious', 'lost'],
    luck_tags: ['newspace', 'health'],
    elements: ['earth', 'wood'],
  },

  // ========== B. 水晶 / 礦石套裝系列（9 款）==========
  // 套裝組成 = 鼠尾草 + 聖木 + 水晶/礦石
  {
    id: 'c1', slug: 'amethyst-cluster-set', name: '紫晶簇 + 5cm 聖木 + 2吋鼠尾草套組',
    subtitle: '全方位淨化入門組',
    description: '集齊三大淨化元素：紫晶簇放大能量、聖木提振、鼠尾草徹底清理。最受歡迎的入門組合，適合所有需求。',
    ingredients: ['紫晶簇', '5cm 聖木', '2吋白鼠尾草束'],
    price: 880, stock: 30, featured: true, created_at: '',
    images: [ph('photo-1567632630891-38b39c12e1a0')],
    category: 'crystal-sets',
    mood_tags: ['anxious', 'lost', 'low'],
    luck_tags: ['unlucky', 'health'],
    elements: ['wind', 'water'],
  },
  {
    id: 'c2', slug: 'aventurine-set', name: '東陵玉原石套裝',
    subtitle: '招財・平衡・心輪',
    description: '東陵玉滋養心輪，平衡情緒並招來財富機會。配上鼠尾草與聖木做完整能量啟動。',
    ingredients: ['東陵玉原石', '聖木', '白鼠尾草'],
    price: 980, stock: 20, featured: false, created_at: '',
    images: [ph('photo-1518057111178-44a106bad636')],
    category: 'crystal-sets',
    mood_tags: ['calm', 'low'],
    luck_tags: ['career', 'health'],
    elements: ['wood'],
  },
  {
    id: 'c3', slug: 'citrine-set', name: '黃水晶原石套裝',
    subtitle: '招財・提振・自信',
    description: '太陽石頭，注入溫暖正能量。事業卡關、信心低落、需要陽性力量時的首選。',
    ingredients: ['黃水晶原石', '聖木', '白鼠尾草'],
    price: 1080, stock: 18, featured: true, created_at: '',
    images: [ph('photo-1591437174033-cef38f59b2b8')],
    category: 'crystal-sets',
    mood_tags: ['low', 'lost'],
    luck_tags: ['career'],
    elements: ['fire', 'earth'],
  },
  {
    id: 'c4', slug: 'fluorite-set', name: '綠螢石原石套裝',
    subtitle: '學業・智慧・專注',
    description: '螢石澄清思緒，幫助下決定。考試、研究、新計畫的能量好夥伴。',
    ingredients: ['綠螢石原石', '聖木', '白鼠尾草'],
    price: 1080, stock: 15, featured: false, created_at: '',
    images: [ph('photo-1518709594023-6eab9bab7b23')],
    category: 'crystal-sets',
    mood_tags: ['lost'],
    luck_tags: ['career', 'newplan'],
    elements: ['wind', 'water'],
  },
  {
    id: 'c5', slug: 'clear-quartz-set', name: '白水晶原石套裝',
    subtitle: '全能・淨化・放大能量',
    description: '水晶之王，能量百搭。可以放大其他水晶的能量，也可獨立做空間淨化主石。',
    ingredients: ['白水晶原石', '聖木', '白鼠尾草'],
    price: 1180, stock: 25, featured: true, created_at: '',
    images: [ph('photo-1548020517-dc78e4a32f97')],
    category: 'crystal-sets',
    mood_tags: ['anxious', 'lost', 'low', 'tired'],
    luck_tags: ['unlucky', 'health'],
    elements: ['wind', 'water', 'earth', 'fire', 'wood'],
  },
  {
    id: 'c6', slug: 'rose-quartz-set', name: '粉紅水晶原石套裝',
    subtitle: '桃花・自我愛・療癒',
    description: '愛之石。打開心輪、療癒情傷、為自己注入更多溫柔。感情低潮的療癒救星。',
    ingredients: ['粉紅水晶原石', '聖木', '白鼠尾草'],
    price: 1180, stock: 22, featured: true, created_at: '',
    images: [ph('photo-1524666041070-9d87656c25bb')],
    category: 'crystal-sets',
    mood_tags: ['low', 'tired'],
    luck_tags: ['romance'],
    elements: ['water'],
  },
  {
    id: 'c7', slug: 'amethyst-set', name: '紫水晶原石套裝',
    subtitle: '智慧・安神・靈性',
    description: '紫水晶安撫心神、助眠、開啟靈性視野。失眠、焦慮、迷茫時最直接的能量平息。',
    ingredients: ['紫水晶原石', '聖木', '白鼠尾草'],
    price: 1280, stock: 20, featured: true, created_at: '',
    images: [ph('photo-1567632630891-38b39c12e1a0')],
    category: 'crystal-sets',
    mood_tags: ['anxious', 'lost'],
    luck_tags: ['health'],
    elements: ['wind'],
  },
  {
    id: 'c8', slug: 'blue-lace-agate-set', name: '藍紋石原石套裝',
    subtitle: '表達・溝通・喉輪',
    description: '溫柔的藍紋石開啟喉輪，幫助清晰表達。職場談判、感情溝通、想為自己發聲時的能量輔助。',
    ingredients: ['藍紋石原石', '聖木', '白鼠尾草'],
    price: 1180, stock: 12, featured: false, created_at: '',
    images: [ph('photo-1572119865084-43c285814d63')],
    category: 'crystal-sets',
    mood_tags: ['angry', 'lost'],
    luck_tags: ['romance', 'career'],
    elements: ['wind', 'water'],
  },
  {
    id: 'c9', slug: 'red-jasper-set', name: '紅碧玉原石套裝',
    subtitle: '力量・勇氣・海底輪',
    description: '紅碧玉激活海底輪，回到身體、回到力量。疲憊、健康下滑、需要勇氣時的能量補品。',
    ingredients: ['紅碧玉原石', '聖木', '白鼠尾草'],
    price: 1080, stock: 16, featured: false, created_at: '',
    images: [ph('photo-1602928298849-325cec8771c0')],
    category: 'crystal-sets',
    mood_tags: ['tired', 'angry'],
    luck_tags: ['health', 'career'],
    elements: ['fire', 'earth'],
  },

  // ========== C. 能量草杖系列（9 款，薰衣草為基底）==========
  {
    id: 'w1', slug: 'wand-orange', name: '薰衣草 + 甜橙 + 聖木 草杖',
    subtitle: '提振活力',
    description: '薰衣草的安撫加上甜橙的陽光感，再以聖木點亮整個空間。低落、需要轉換氛圍時的能量泡澡。',
    ingredients: ['薰衣草', '甜橙', '祕魯聖木'],
    price: 580, stock: 18, featured: false, created_at: '',
    images: [ph('photo-1599623560574-39d485900c95')],
    category: 'energy-wands',
    mood_tags: ['low', 'tired'],
    luck_tags: ['unlucky'],
    elements: ['fire', 'wood'],
  },
  {
    id: 'w2', slug: 'wand-cinnamon', name: '薰衣草 + 桂皮 + 聖木 草杖',
    subtitle: '招財家宅',
    description: '桂皮是傳統招財香料，配上薰衣草與聖木建構家宅守護。新搬家、想為事業聚財時的儀式良品。',
    ingredients: ['薰衣草', '桂皮', '祕魯聖木'],
    price: 680, stock: 15, featured: true, created_at: '',
    images: [ph('photo-1568571780765-9276ac8b75a2')],
    category: 'energy-wands',
    mood_tags: ['lost'],
    luck_tags: ['career', 'newspace'],
    elements: ['fire', 'earth'],
  },
  {
    id: 'w3', slug: 'wand-rose-eucalyptus', name: '薰衣草 + 迷迭香 + 玫瑰花 + 尤加利葉 草杖',
    subtitle: '全方位療癒',
    description: '四種療癒香草交織：薰衣草安神、迷迭香清晰、玫瑰滋養、尤加利淨化。完整的能量療癒組合。',
    ingredients: ['薰衣草', '迷迭香', '玫瑰花', '尤加利葉'],
    price: 780, stock: 12, featured: false, created_at: '',
    images: [ph('photo-1502209524164-acea936639a2')],
    category: 'energy-wands',
    mood_tags: ['tired', 'low'],
    luck_tags: ['health'],
    elements: ['water', 'wood', 'wind'],
  },
  {
    id: 'w4', slug: 'wand-cedar', name: '薰衣草 + 雪松 草杖',
    subtitle: '安神扎根',
    description: '極簡兩元素配方：薰衣草柔軟撫慰，雪松堅實扎根。失眠、焦慮、需要回到大地感的最直接療癒。',
    ingredients: ['薰衣草', '雪松'],
    price: 580, stock: 20, featured: true, created_at: '',
    images: [ph('photo-1542728928-1413d1894ed1')],
    category: 'energy-wands',
    mood_tags: ['anxious'],
    luck_tags: ['health'],
    elements: ['earth', 'wood'],
  },
  {
    id: 'w5', slug: 'wand-forget-me-not', name: '薰衣草 + 勿忘我 + 玫瑰花 + 白水晶 草杖',
    subtitle: '感情療癒',
    description: '本店招牌。勿忘我承載思念、玫瑰滋養愛、白水晶放大療癒。感情低潮的溫柔擁抱。',
    ingredients: ['薰衣草', '勿忘我', '玫瑰花', '白水晶碎'],
    price: 880, stock: 10, featured: true, created_at: '',
    images: [ph('photo-1518709779341-56cf4535e94b')],
    category: 'energy-wands',
    mood_tags: ['low', 'tired'],
    luck_tags: ['romance'],
    elements: ['water'],
  },
  {
    id: 'w6', slug: 'wand-mum-quartz', name: '薰衣草 + 迷迭香 + 七彩菊 + 水晶柱 草杖',
    subtitle: '創造力轉運',
    description: '七彩菊象徵綻放、水晶柱聚焦能量、迷迭香啟發靈感。新計畫、創作瓶頸、想轉運時的儀式選擇。',
    ingredients: ['薰衣草', '迷迭香', '七彩菊', '水晶柱'],
    price: 880, stock: 12, featured: false, created_at: '',
    images: [ph('photo-1487530811176-3780de880c2d')],
    category: 'energy-wands',
    mood_tags: ['joyful', 'lost'],
    luck_tags: ['newplan', 'career'],
    elements: ['fire', 'wind'],
  },
  {
    id: 'w7', slug: 'wand-sage-palo', name: '薰衣草 + 雪松 + 白鼠尾草 + 聖木 草杖',
    subtitle: '強力淨化',
    description: '結合四大淨化元素：鼠尾草徹底清理、聖木提振、雪松扎根、薰衣草安撫。搬家、氣場混亂、強力轉場必備。',
    ingredients: ['薰衣草', '雪松', '白鼠尾草', '祕魯聖木'],
    price: 880, stock: 14, featured: true, created_at: '',
    images: [ph('photo-1600880292203-757bb62b4baf')],
    category: 'energy-wands',
    mood_tags: ['angry', 'anxious'],
    luck_tags: ['unlucky', 'newspace'],
    elements: ['fire', 'wood', 'earth'],
  },
  {
    id: 'w8', slug: 'wand-baby-breath', name: '薰衣草 + 迷迭香 + 滿天星星 + 玫瑰花 草杖',
    subtitle: '浪漫感情',
    description: '夢幻配方。滿天星星與玫瑰交織出浪漫，配上薰衣草與迷迭香的清晰。約會儀式、感情滋養的能量小詩。',
    ingredients: ['薰衣草', '迷迭香', '滿天星', '玫瑰花'],
    price: 780, stock: 13, featured: false, created_at: '',
    images: [ph('photo-1561181286-d3fee7d55364')],
    category: 'energy-wands',
    mood_tags: ['calm', 'joyful'],
    luck_tags: ['romance'],
    elements: ['water', 'wind'],
  },
  {
    id: 'w9', slug: 'wand-selenite', name: '薰衣草 + 白石膏 + 聖木 草杖',
    subtitle: '神聖空間',
    description: '白石膏（透石膏）淨化純粹，聖木點化空間。新空間入住、設立祭壇、創造儀式場域時的開光必備。',
    ingredients: ['薰衣草', '白石膏', '祕魯聖木'],
    price: 880, stock: 11, featured: false, created_at: '',
    images: [ph('photo-1518709779341-56cf4535e94b')],
    category: 'energy-wands',
    mood_tags: ['calm'],
    luck_tags: ['newspace', 'newplan'],
    elements: ['wind', 'earth'],
  },
]

// 依分類取商品
export function getByCategory(category: string): Product[] {
  if (category === 'all') return PRODUCTS
  return PRODUCTS.filter((p) => p.category === category)
}

// 依 slug 取商品
export function getBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug)
}

// 取精選商品
export function getFeatured(limit: number = 4): Product[] {
  return PRODUCTS.filter((p) => p.featured).slice(0, limit)
}
